name: 'Terraform'

on:
  push:
    branches:
      - "0"
    paths-ignore:
      - "**"

jobs:
  Terraform:
    name: "Terraform"
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4


    # Install the latest version of Terraform CLI and configure the Terraform ration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: cd spoke
      run : cd spoke

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    - name: terraform workspace select
      run: terraform workspace select PROD

      # On push to "main", build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Terraform Apply
      run: terraform apply -destroy -auto-approve -input=false -var-file=variables/PROD.tfvars


